repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.1.0
  hooks:
  - id: reorder-python-imports
    language_version: python3
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "100"]
    language_version: python3
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
    language_version: python3
  - id: end-of-file-fixer
    language_version: python3
  - id: debug-statements
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    language_version: python3
- repo: https://github.com/asottile/pyupgrade
  rev: v2.1.0
  hooks:
  - id: pyupgrade
    language_version: python3
